### ISSUE TITLE
Depending on older versions of React Native

### ISSUE THREAD

**Issue by arrygoo** [singular-labs/react-native-sdk#18]
Hello,
I hope you're doing well. 

Our team is considering using this SDK, but I see that the react-native version in `package.json` of this project is very outdated. I wanted to reach out to ask if this package is often maintained, and if there's any reason the react-native dependency is a few versions behind. Has this SDK been tested with newer versions of React Native like 0.63? 

Thanks in advance

**Comment by eyalsingular** [comment]
Hi @arrygoo, Thanks for reaching out!

Don't be alarmed by the old react native version in the package json, it's the minimum version supported by our SDK.
This package is maintained relatively often and supports the newest react-native versions.

Cheers,
Eyal
