### ISSUE TITLE
Error installing yesterday: Couldn't find com.singular.sdk:singular_sdk:9.+

### ISSUE THREAD

**Issue by morleyzhi** [singular-labs/react-native-sdk#24]
Yesterday, we discovered we couldn't build our React Native project due to this error. 

It seems like you published com.singular.sdk 11.0, but this breaks RN, which requires 9+:
http://maven.singular.net/com/singular/sdk/singular_sdk/maven-metadata.xml

Reproduced this when importing singular-react-native 1.0.4 and 1.1.6.

This is the full error:

```
* What went wrong:
Could not determine the dependencies of task ':app:mergeDevDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find any version that matches com.singular.sdk:singular_sdk:9.+.
     Versions that do not match: 11.0.0
     Searched in the following locations:
       - file:/Users/morley/.m2/repository/com/singular/sdk/singular_sdk/
       - file:/Users/morley/Projects/mobile-wallet/node_modules/react-native/android/com/singular/sdk/singular_sdk/maven-metadata.xml
       - file:/Users/morley/Projects/mobile-wallet/node_modules/jsc-android/dist/com/singular/sdk/singular_sdk/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/singular/sdk/singular_sdk/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/singular/sdk/singular_sdk/maven-metadata.xml
       - https://mobile-sdk.jumio.com/com/singular/sdk/singular_sdk/maven-metadata.xml
       - https://www.jitpack.io/com/singular/sdk/singular_sdk/maven-metadata.xml
       - file:/Users/morley/Projects/mobile-wallet/node_modules/detox/Detox-android/com/singular/sdk/singular_sdk/maven-metadata.xml
       - http://maven.singular.net/com/singular/sdk/singular_sdk/maven-metadata.xml
       - file:/Users/morley/Projects/mobile-wallet/android/libs/
     Required by:
         project :app > project :singular-react-native
```

**Comment by FedeCarrizo30** [comment]
Same error here 💀

**Comment by eyalsingular** [comment]
Hi @morleyzhi and @FedeCarrizo30,

Thank you for bringing this to our attention .
We released a new version (1.1.7) with a fix to that dependency, please let me know if you encounter this issue again.

Cheers,
Eyal

**Comment by tplorts** [comment]
@eyalsingular thanks for the quick fix there!  Worked for us as well.

Since this updates the android sdk from 9 to 11, should we be aware of any major or breaking changes on android?
I didn’t see any entry for v11 on the changelog: https://support.singular.net/hc/en-us/articles/360041068651-Android-SDK-Change-Log

**Comment by eyalsingular** [comment]
Hi @tplorts,

There are no breaking changes, we treat backwards compatibility with great importance.
Documentation will be uploaded in the next few days.

Cheers,
Eyal

**Comment by morleyzhi** [comment]
We confirmed on Friday that this is fixed, so I'll close the issue.  Thanks!

**Comment by MalekZishan** [comment]
allprojects {
  repositories {
    maven { url 'https://maven.singular.net/' }
  }
}


resolve this
