### ISSUE TITLE
Undocumented AppDelegate methods

### ISSUE THREAD

**Issue by toddtreece** [singular-labs/react-native-sdk#7]
The [integration guide](https://support.singular.net/hc/en-us/articles/360038415852) doesn't mention these methods. Are they required in the `AppDelegate` in order to implement deep links?
https://github.com/singular-labs/react-native-sdk/blob/41cbdeaf098502a6d6cd8f1ec7b0b2d884e18ea4/ios/SingularBridge.m#L28-L47

**Comment by toddtreece** [comment]
i tested this with a boilerplate react-native app to make sure it wasn't something else causing the issue, and i can confirm that these two undocumented methods are needed for deep links to work properly

**Comment by eyalsingular** [comment]
Thanks @toddtreece! we have added them to our documentation.
