### ISSUE TITLE
Auto linking for React Native 0.60+

### ISSUE THREAD

**Issue by toddtreece** [singular-labs/react-native-sdk#8]
We are using react-native 0.62.2, and it seems like iOS auto linking is not working as expected with this package.

I had to add the following line to our `Podfile`:

```
  pod 'Singular-React-Native', :path => "../node_modules/singular-react-native"
```

**Comment by ram95krishh** [comment]
Experiencing the same in iOS at my end. Even after adding this to Podfile it says...
`Native modules cannot be null`
![Uploading IMG_0590.PNG…]()

**Comment by IamDixit** [comment]
Auto-Linking is broken and not working for RN 0.62.2, need to manually add `pod 'Singular-React-Native', :path => "../node_modules/singular-react-native"` in podfile to fix this issue

**Comment by ram95krishh** [comment]
The error I reported above was probably from a cache issue in my system, it is gone now and the SDK works! Nevertheless you guys have to check if your auto-linking is broken in RN 0.62.2 or add instructions to your iOS setup to include this line in the Podfile
`pod 'Singular-React-Native', :path => "../node_modules/singular-react-native"`
Only after which the following Pods got installed
![image](https://user-images.githubusercontent.com/45874777/95162041-4bb2f000-07c2-11eb-9d45-7a9f3a431a4a.png)
