### ISSUE TITLE
TS2305: Module  "singular-react-native"  has no exported member  Events

### ISSUE THREAD

**Issue by dbacinski** [singular-labs/react-native-sdk#82]
I am trying to:

`import {Events} from "singular-react-native"`

to get standard events but I get an error:

`TS2305: Module  "singular-react-native"  has no exported member  Events`

It seems like TS type definition is missing in:

https://github.com/singular-labs/react-native-sdk/blob/master/index.d.ts

**Comment by Johann01** [comment]
Also the function  adRevenue(adData) and SingularData is not exposed. Will the missing type definitions be added?

**Comment by shefdanny** [comment]
Thanks for bringing this to our attention. solved in version 3.5.2
